// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-A6H8pGcVBpXNtz9FFkMz9zxKkDJnW1I',
    appId: '1:64267650521:web:d64559365cb247660005c8',
    messagingSenderId: '64267650521',
    projectId: 'healthcard-eb670',
    authDomain: 'healthcard-eb670.firebaseapp.com',
    storageBucket: 'healthcard-eb670.appspot.com',
    measurementId: 'G-WNKF7NER6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-iJTw9PJ8aQxi8RkjLBEEVFiobfhkulE',
    appId: '1:64267650521:android:3e7fba3d5500d0bd0005c8',
    messagingSenderId: '64267650521',
    projectId: 'healthcard-eb670',
    storageBucket: 'healthcard-eb670.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD53kPaJiOYpraolEskp5a2ubXiaXuyS8A',
    appId: '1:64267650521:ios:d9fdcc55e8e2d9950005c8',
    messagingSenderId: '64267650521',
    projectId: 'healthcard-eb670',
    storageBucket: 'healthcard-eb670.appspot.com',
    iosBundleId: 'com.example.medicinedispenser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD53kPaJiOYpraolEskp5a2ubXiaXuyS8A',
    appId: '1:64267650521:ios:d9fdcc55e8e2d9950005c8',
    messagingSenderId: '64267650521',
    projectId: 'healthcard-eb670',
    storageBucket: 'healthcard-eb670.appspot.com',
    iosBundleId: 'com.example.medicinedispenser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-A6H8pGcVBpXNtz9FFkMz9zxKkDJnW1I',
    appId: '1:64267650521:web:7711c64d0ff863ce0005c8',
    messagingSenderId: '64267650521',
    projectId: 'healthcard-eb670',
    authDomain: 'healthcard-eb670.firebaseapp.com',
    storageBucket: 'healthcard-eb670.appspot.com',
    measurementId: 'G-HSPBE1G3CN',
  );
}
